global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sims-backend'
    static_configs:
      - targets: ['backend-1:5000', 'backend-2:5000', 'backend-3:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-primary:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']