#!/bin/bash

# SchoolSync Enterprise Deployment Script
# Deploys both main and admin frontends with HTTPS certificates

echo "🚀 Starting SchoolSync Enterprise Deployment..."
echo "📋 Main Frontend: https://school-sync.org (Port 443)"
echo "🔧 Admin Frontend: https://schoolsyncadmin.duckdns.org:445 (Port 445)"
echo ""

# Check if Docker and Docker Compose are available
if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed. Please install Docker first."
    exit 1
fi

if ! command -v docker-compose &> /dev/null; then
    echo "❌ Docker Compose is not installed. Please install Docker Compose first."
    exit 1
fi

# Stop any existing containers
echo "🛑 Stopping existing containers..."
docker-compose -f docker-compose-enterprise.yml down

# Build and start the enterprise stack
echo "🔨 Building and starting enterprise stack..."
docker-compose -f docker-compose-enterprise.yml up --build -d

# Wait for services to be healthy
echo "⏳ Waiting for services to start..."
sleep 30

# Check service health
echo "🔍 Checking service health..."
docker-compose -f docker-compose-enterprise.yml ps

echo ""
echo "✅ SchoolSync deployment complete!"
echo ""
echo "📱 Access Points:"
echo "   Main App:  https://school-sync.org"
echo "   Admin App: https://schoolsyncadmin.duckdns.org:445"
echo "   Grafana:   http://localhost:3001 (admin/admin123)"
echo "   Prometheus: http://localhost:9090"
echo ""
echo "🔐 SSL certificates will be automatically generated by Let's Encrypt"
echo "📊 Monitoring stack is available for performance tracking"
echo ""